source 'https://rubygems.org'

# Specify your gem's dependencies in utcd.gemspec
gemspec

gem 'apfel'
gem 'graphql-client'
gem 'rake', '~> 12.0'
gem 'rest-client', '~> 2.0'
gem 'rspec', '~> 3.0'
gem 'nokogiri'
gem 'readapt'
